name: CI/CD para Back-End na EC2 pública e privada

on:
  push:
    branches:
      - main # O branch que acionará o deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: tech4good
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:

      # 1. Checkout do código
      - name: Checkout do Repositório
        uses: actions/checkout@v4

       # 2. Configuração do ambiente Java/Maven
      - name: BE - Configurar JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto' # ou a distribuição que preferir
          java-version: '21'
          cache: 'maven' # Configura cache do Maven para acelerar builds futuros
      

      # 3. Execução dos testes automatizados do projeto
      - name: BE - Executar Testes automatizados
        run: mvn clean test      
        working-directory: ./Tech4Good_API

      # 4. Geração do .jar
      - name: BE - Gerar Artefato .JAR
        run: mvn package -DskipTests=true # -DskipTests=true pq os testes foram executados no passo anterior
        working-directory: ./Tech4Good_API

      # 5. Dando o mesmo nome sempre ao .jar
      - name: BE - Renomear JAR para app.jar # ou o nome que preferir parta o jar
        run: |
          # Encontra o primeiro (e único) arquivo .jar gerado na pasta 'target'
          # e o renomeia para o nome fixo.
          # O comando 'ls target/*.jar' retorna o nome original.
          
          JAR_NAME=$(ls target/*.jar)
          
          # Renomeia o arquivo.
          mv $JAR_NAME target/app.jar
          
          echo "Renomeado para: target/app.jar"
        working-directory: ./Tech4Good_API

      # 6. Preparar diretório na Web1
      - name: BE - Preparar diretório backend na Web1
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Remove arquivo ou diretório antigo
            rm -rf /home/${{ secrets.REMOTE_USER }}/backend
            # Cria diretório limpo
            mkdir -p /home/${{ secrets.REMOTE_USER }}/backend
            echo "✅ Diretório /home/${{ secrets.REMOTE_USER }}/backend preparado"

      # 7. Deploy (Transferência de arquivos e execução de comandos remotos)
      - name: BE - Copiar arquivos e Deploy (Usando SSH com rsync)
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /home/${{ secrets.REMOTE_USER }}/backend/
          # ARGS para rsync: -rltgoDzvO para cópia recursiva, compressão e outros
          ARGS: "-rltgoDzvO" 
          # SOURCE: O que será copiado. Apenas o .jar gerado no build
          SOURCE: './Tech4Good_API/target/'
          

      # 8. Fazendo o envio do jar da ec2 pública para a privada
      - name: BE - Executar Comando Shell na EC2
        uses: appleboy/ssh-action@v1.0.3 # Action popular para SSH
        with:
          host: ${{ secrets.REMOTE_HOST }} 
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}  

          # O Comando ou Script a ser Executado no EC2
          # Use o pipe '|' para comandos de múltiplas linhas
          script: |
            set -e
            
            echo "=========================================="
            echo "🚀 Iniciando deploy do backend na EC2 privada"
            echo "=========================================="
            
            # criando um .pem temporário, baseado no secret do github
            ARQUIVO_PEM="/home/${{ secrets.REMOTE_USER }}/chavetmp.pem"
            echo "📝 Criando arquivo PEM temporário: $ARQUIVO_PEM"

            # excluindo o arquivo .pem, caso exista
            rm -f $ARQUIVO_PEM
            echo "✅ Arquivo .pem anterior removido (se existia)"
            
            echo "${{ secrets.EC2_SSH_KEY }}" > $ARQUIVO_PEM || true
            chmod 400 $ARQUIVO_PEM || true
            
            # Verificar se o arquivo foi criado
            if [ ! -f "$ARQUIVO_PEM" ]; then
              echo "❌ ERRO: Arquivo PEM não foi criado!"
              exit 1
            fi
            echo "✅ Arquivo PEM criado com permissões corretas"
            
            # Verificar tamanho do arquivo (debug)
            ls -lh $ARQUIVO_PEM

            # usuario e ip de destino
            USUARIO_IP=${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST_PRIVADO }}
            echo "🌐 Target: $USUARIO_IP"
            echo ""
            
            echo "🔍 Testando conectividade com a instância privada..."
            # Testar conexão SSH com timeout de 30 segundos
            if ssh -o ConnectTimeout=30 -o StrictHostKeyChecking=no -i $ARQUIVO_PEM $USUARIO_IP 'echo "✅ Conexão SSH estabelecida com sucesso!"'; then
              echo "✅ Conectividade OK"
            else
              echo "❌ ERRO: Não foi possível conectar à instância privada"
              echo "   Verifique:"
              echo "   1. Security Group permite SSH do web_sg"
              echo "   2. Instância privada está rodando"
              echo "   3. Chave SSH está configurada no authorized_keys"
              exit 1
            fi
            echo ""

            # Garante que o diretório existe na EC2 privada
            echo "📁 Criando diretório /usr/share/api/ na instância privada..."
            ssh -o ConnectTimeout=30 -o StrictHostKeyChecking=no -i $ARQUIVO_PEM $USUARIO_IP 'sudo mkdir -p /usr/share/api/'

            echo "✅ Diretório criado"
            echo ""
            
            # Envia o .jar para o home do usuário
            echo "📦 Transferindo app.jar para a instância privada..."
            echo "   Origem: /home/${{ secrets.REMOTE_USER }}/backend/app.jar"
            echo "   Destino: /home/ubuntu/app.jar"
            
            if scp -o ConnectTimeout=30 -o StrictHostKeyChecking=no -i $ARQUIVO_PEM /home/${{ secrets.REMOTE_USER }}/backend/app.jar $USUARIO_IP:/home/ubuntu/app.jar; then
              echo "✅ Arquivo transferido com sucesso"
            else
              echo "❌ ERRO: Falha ao transferir o arquivo JAR"
              exit 1
            fi
            echo ""

            # Move com sudo para o destino final
            echo "📂 Movendo JAR para /usr/share/api/..."
            ssh -o ConnectTimeout=30 -o StrictHostKeyChecking=no -i $ARQUIVO_PEM $USUARIO_IP 'sudo mv /home/ubuntu/app.jar /usr/share/api/app.jar && sudo chown root:root /usr/share/api/app.jar'
            echo "✅ JAR movido para /usr/share/api/app.jar"
            echo ""

            # Para o container da API (se estiver rodando)
            echo "🛑 Parando container da API..."
            ssh -o ConnectTimeout=30 -o StrictHostKeyChecking=no -i $ARQUIVO_PEM $USUARIO_IP 'sudo docker stop api-spring || true'
            echo "✅ Container parado"
            echo ""

            # Remove o container antigo (força recriação)
            echo "🗑️  Removendo container antigo..."
            ssh -o ConnectTimeout=30 -o StrictHostKeyChecking=no -i $ARQUIVO_PEM $USUARIO_IP 'sudo docker rm api-spring || true'
            echo "✅ Container removido"
            echo ""

            # Sobe o container da API novamente (garante que pegue o novo JAR)
            echo "🚀 Iniciando container da API com o novo JAR..."
            ssh -o ConnectTimeout=30 -o StrictHostKeyChecking=no -i $ARQUIVO_PEM $USUARIO_IP 'sudo docker run -d --name api-spring --restart unless-stopped -v /usr/share/api:/usr/share/api -p 8080:8080 --network tech4good-network -e SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/tech4good -e SPRING_DATASOURCE_USERNAME=tech4good -e SPRING_DATASOURCE_PASSWORD=tech4good123 amazoncorretto:21 sh -c "java -jar /usr/share/api/app.jar"'
            echo "✅ Container iniciado"
            echo ""

            # Aguarda container inicializar
            echo "⏳ Aguardando 5 segundos para o container inicializar..."
            sleep 5
            
            # Verifica se o container está rodando
            echo "🔍 Verificando se o container está rodando..."
            if ssh -o ConnectTimeout=30 -o StrictHostKeyChecking=no -i $ARQUIVO_PEM $USUARIO_IP 'sudo docker ps | grep api-spring'; then
              echo "✅ Container está rodando!"
            else
              echo "⚠️  Container não encontrado, verificando logs..."
              ssh -o ConnectTimeout=30 -o StrictHostKeyChecking=no -i $ARQUIVO_PEM $USUARIO_IP 'sudo docker-compose -f /home/ubuntu/compose.yaml logs api --tail=50'
            fi
            
            echo ""
            echo "=========================================="
            echo "✅ Deploy do back-end concluído com sucesso!"
            echo "=========================================="
            
            # Limpar arquivo PEM temporário por segurança
            rm -f $ARQUIVO_PEM
            echo "🧹 Arquivo PEM temporário removido"
